spring:
  application:
    name: arka-backend
  datasource:
    url: jdbc:h2:mem:arkadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS inventory\;CREATE SCHEMA IF NOT EXISTS ordering\;CREATE SCHEMA IF NOT EXISTS cart\;CREATE SCHEMA IF NOT EXISTS notification\;CREATE SCHEMA IF NOT EXISTS analytics\;CREATE SCHEMA IF NOT EXISTS shared
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
    tcp:
      enabled: true
      port: 9092

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.arka.backend: INFO
    org.springframework.web: INFO
